### ISSUE TITLE
Can we reduce the minimun iOS target version to 11 or 12?

### ISSUE THREAD

**Issue by phucgaoxam** [Unleash/unleash-proxy-client-swift#11]
Current minimun requirement for iOS is 13, it's a little bit high

**Comment by vanbungkring** [comment]
bump up!

**Comment by ivarconr** [comment]
Does anyone have insights in to which code changes this would require?

**Comment by phucgaoxam** [comment]
I think the code is for Poller feature

**Comment by chickdan** [comment]
Our team is very excited to use Unleash but this is currently a deal-breaker as our product has users across a large spectrum of iOS versions. Dropping to iOS 11 is ideal, what's the possibility of this and if the Unleash team needs help how can we be of assistance?

**Comment by FredrikOseberg** [comment]
I'm currently looking into what this would require.

**Comment by FredrikOseberg** [comment]
> Our team is very excited to use Unleash but this is currently a deal-breaker as our product has users across a large spectrum of iOS versions. Dropping to iOS 11 is ideal, what's the possibility of this and if the Unleash team needs help how can we [consumers] be of assistance?

@chickdan I've tried just outright lowering the version requirements and could not find any issues with that on my end. Would you be able to verify this library via this branch on your end. See #12.

**Comment by chickdan** [comment]
@FredrikOseberg Thank you for the quick turnaround! When we attempted to build our project after importing the new branch via SPM we did receive a few compile-time errors, as you can see in the screenshots attached below:

<img width="1072" alt="Screen Shot 2021-12-20 at 12 40 49 PM" src="https://user-images.githubusercontent.com/8951682/146837189-9a9b0fdd-6c64-46f6-a2b4-20d1dd374f9a.png">
<img width="1072" alt="Screen Shot 2021-12-20 at 12 41 16 PM" src="https://user-images.githubusercontent.com/8951682/146837194-0821b60e-b2a7-471e-b0d4-bdf7aad81103.png">

**Comment by FredrikOseberg** [comment]
> @FredrikOseberg Thank you for the quick turnaround! When we attempted to build our project after importing the new branch via SPM we did receive a few compile-time errors, as you can see in the screenshots attached below:
> 
> <img alt="Screen Shot 2021-12-20 at 12 40 49 PM" width="1072" src="https://user-images.githubusercontent.com/8951682/146837189-9a9b0fdd-6c64-46f6-a2b4-20d1dd374f9a.png">
> 
> <img alt="Screen Shot 2021-12-20 at 12 41 16 PM" width="1072" src="https://user-images.githubusercontent.com/8951682/146837194-0821b60e-b2a7-471e-b0d4-bdf7aad81103.png">

Thanks for checking it out. Unfortunately it seems to require some changes to the actual library, and I don't think we can get to this before sometime next year. If you have the time and resources, I'm happy to review a PR that fixes these issues faster.

**Comment by aragonet** [comment]
Is there any forecast of when it will be possible to use the sdk without needing to force iOS version 13.0?

Thanks in advance

**Comment by pnzr00t** [comment]
Hello i made small MR for downgrade to IOS v12 version, maybe it may work in v11, or less, but i not testing that. Link to MR below

https://github.com/Unleash/unleash-proxy-client-swift/pull/34
