### ISSUE TITLE
Metrics support

### ISSUE THREAD

**Issue by thedotedge** [Unleash/unleash-proxy-client-swift#28]
### Describe the feature request

Hi,
I have noticed that Swift proxy client does not currently report metrics. Do you plan to add metrics support as per https://docs.getunleash.io/api/client/metrics? 

### Background

[JS Client](https://github.com/Unleash/unleash-proxy-client-js/blob/main/README.md) already supports it, so getting this to work on iOS would be a nice feature.

**Comment by pransh15** [comment]
Hey @thedotedge 👋  

Thanks for sharing this feature request. I'll check with the team for a quick status and if there are no immediate plans, would you like to help out and contribute to the project?

**Comment by thedotedge** [comment]
Thanks @sighphyre! Swift is not really my cup of tea though 😅 @loongman would it be something interesting for you?

**Comment by sighphyre** [comment]
@thedotedge Completely understand, you and me both!

I'm going to pin this for now so it doesn't get closed by our bot or forgotten about

**Comment by kwasniew** [comment]
Metrics support added in https://github.com/Unleash/unleash-proxy-client-swift/releases/tag/0.0.7
