### ISSUE TITLE
Is there any plan to cache to flags?

### ISSUE THREAD

**Issue by vintersnow** [Unleash/unleash-proxy-client-swift#30]
### Describe the feature request

I prefer to cache flags into the local storage.

### Background

When launching the app for the second time, I want to access the flags as soon as possible. I mean that I want access to the flags before the SDK has been initialized.

### Solution suggestions

I thought changing the isEnabled function to async was not good so I cache the flags to the userdefault when the SDK is ready and updated.

**Comment by vintersnow** [comment]
Sorry for being late in responding. 
I use feature flags to AB test some UI in the Home view (the first view users see when they launch the app).
So I needed the feature flag when the app launched and this happened before the unleash client was ready.
If the flag is not ready, then it becomes false so that the user will be in and out of the AB group while testing.
That is why I need to cache the flags.
I know caching the flags will be a problem when we change the strategy but it is quite rare in my project (It tends to fix while AB testing).
It would be great if we could handle this use case on the SDK side.
Thank you.

**Comment by nunogois** [comment]
Hi @vintersnow, no worries, thank you for your reply!

The way I see it, you may be able to tackle your use case by subscribing to the `ready` event on the Unleash client, just like it's described in the README - That way you could wait until the client is ready so you can always display the correct information to your end users.

Like you mentioned, there's a risk caching the flags may result in wrong behavior if one of your features changes server side, as the end user will get the wrong result until it syncs.

We've discussed this internally and it's something we may consider adding to our backlog.
Of course, you're always free to open a PR if you have any ideas and we'd be more than happy to guide you through it and review your contribution.

Hopefully this helps, and thank you again for sharing!

**Comment by vintersnow** [comment]
Thank you.
Yes, I already use "ready" and "update" hooks and wondering any way not to wait the user for the UX.
I will try warming up the SDK before launching and reducing the start-up time.
Anyway, I think we can close this issue. Thanks again.

**Comment by marianhunchak** [comment]
Hey, guys, we have the same issue with caching in our setup. We need on second run to retrieve feature status as early as possible and don't wan't to load response body if there are no changes. So currently on first run we download features and store them in local storage with ETag, on next run we just check whether send GET request with stored ETag and in case of 304 we are just using feature from local storage. So we don't need to load hundreds of feature every time and also could use already stored in local memory. We are not changing feature statuses that often, so it would be better for us not load them if nothing has changed, as we have apps with hundreds of features.

Could you consider adding possibility to choose caching options like: inMemory or localStorage? And in case of localeStore cache ETage as metadata to not load repsonse body every time on app run if there are no changes.
