### ISSUE TITLE
Version 0.0.7 Package Description has and uncompatible minimum iOS version

### ISSUE THREAD

**Issue by didac-calventus** [Unleash/unleash-proxy-client-swift#39]
### Describe the bug

Project build fails after updating to 0.0.7 with SPM

Those are the errors:

<img width="745" alt="image" src="https://github.com/Unleash/unleash-proxy-client-swift/assets/10064173/6d264a46-5e05-40ed-a730-8fc3dbe0303c">

Comparing the PackageDescription from 0.0.6 to 0.0.7 we see that on `platforms` the iOS version has been downgraded from `.iOS(.v13)` to `.iOS(.v12)`.

If the downgrade on the iOS version is intended, then the files using concurrency are the ones that should be fixed.

### Steps to reproduce the bug

1. Update the 'unleash-proxy-client-swift' Package  to version 0.0.7 
2. build the project.
3. the build fails because concurrency needs iOS 13

### Additional context

XCode 14.3, dependencies managed with Swift Package Manager

### Unleash version

0.0.7

### Subscription type

None

### Hosting type

None

**Comment by daveleek** [comment]
Thank you for the bug report @didac-calventus! We'll have a look!

**Comment by alamos-gmbh** [comment]
I opened a PR
Not sure about the MacOS version, though.
Tested with Xcode 14.2 against iOS 16.5
Compiles & Installs again
Plain 0.0.7 was not working
