### ISSUE TITLE
add an extra context param into the constructor of UnleashClient

### ISSUE THREAD

**Issue by compfall** [Unleash/unleash-proxy-client-swift#4]
Currently the constructor only accept appName and environment. 
So for adding more context. we have to add one by one the context after the init or use UpdateContext(), which will stop and start the proxy right away. 

In order to accommodate to different needs of different project.
It would be better to add an extra context param in the constructor of the UnleashClient. 
So we can pass more contexts during the init of the UnleashClient.

**Comment by FredrikOseberg** [comment]
Thanks! I agree that it would be beneficial to setup the context from the initialization to prevent restarting the poller. Adding labels to this in case someone can grab this issue before I have time to get to it.
