### ISSUE TITLE
Metric supported for iOS

### ISSUE THREAD

**Issue by tumlw** [Unleash/unleash-proxy-client-swift#40]
### Describe the feature request

Recently I used Unleash and of-course this product really heplfull.
How about metric record? and about release plan?

I saw mr 4 days ago for "metric"

**Comment by daveleek** [comment]
Thank you for your suggestion @tumlw! We'll have a look at it!

**Comment by vandyshev** [comment]
🤦‍♂️

**Comment by kwasniew** [comment]
@tumlw version 0.0.8 supports metrics
