### ISSUE TITLE
Support stop timer at metrics class

### ISSUE THREAD

**Issue by zankyn123** [Unleash/unleash-proxy-client-swift#44]
### Describe the feature request

Stop timer for metrics class

### Background

We are developing an application that includes a login logout function, every time a user logs in we will
call updateContext function of UnleashClient class, with poller every time updateContext the timer will be released but with metrics not released, this has gradually caused the request api metrics to be generated corresponding to the number of calls to the updateContext func, this doesn't seem dangerous but really for network it will be bad if updateContext function is called too much

### Solution suggestions

I think add code stop timer like timer of Poller class

**Comment by kwasniew** [comment]
@zankyn123 This should fix the issue: https://github.com/Unleash/unleash-proxy-client-swift/pull/45
