### ISSUE TITLE
Add support for tvOS

### ISSUE THREAD

**Issue by octover** [Unleash/unleash-proxy-client-swift#52]
### Describe the feature request

We use Unleash on tvOS as well as iOS. We always have to manually edit the Swift Package after updating or when it is pulled in fresh to add tvOS support.

It's simply a matter of adding it to the @available in UnleashProxyClientSwift.swift
```swift
@available(iOS 13, tvOS 13, *)
public class UnleashClient: UnleashClientBase, ObservableObject {
}
```

**Comment by kwasniew** [comment]
@octover Will add it soon

**Comment by kwasniew** [comment]
Added

**Comment by octover** [comment]
Thank you for the quick turn around.
