### ISSUE TITLE
The Context has the wrong type

### ISSUE THREAD

**Issue by hypermats** [Unleash/unleash-proxy-client-swift#54]
### Describe the bug

The [documentation](https://docs.getunleash.io/reference/unleash-context) says that custom properties can be passed to unleash in the context's `properties` field of type Map<string,string>.

However, the unleash-proxy-client-swift version of UnleashClient has a context property of type `[String:String]` making it impossible to pass a dictionary in with custom properties.

### Steps to reproduce the bug

1. Initialise an `UnleashClient`
2. Try to come up with code for calling `updateContext` and setting custom properties

Result: Try as you might, you can't . 

### Expected behavior

I expect to have a working way of adding custom properties to the properties field in the context.

perhaps the function signature could be changed to

`public func updateContext(context: [String: String], properties: [String:String]? = nil) -> Void`

I could try myself but I'm unclear as to how to pass the parameter map since the context appears to be sent in the URL parameters.

### Unleash version

Unleash 5.2.8

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

iOS SDK 0.0.11

**Comment by hypermats** [comment]
At a colleagues suggestion I tried skipping the concept of a `parameters` property and just adding all the properties directly in the context dictionary, and this seems to work. 

I had a flag condition on a value checking a custom property. If I provided the custom property directly in the context dictionary, the condition worked.

Is this expected? Not sure if this is just a matter of documentation then?

**Comment by kwasniew** [comment]
@hypermats It looks like a bug in the swift SDK. If you talk directly to the Frontend API then setting custom properties together with the standard properties in a flat string map will work. However if you go through the Edge proxy it will not. Since we want to encourage people to use the nested properties for the custom stuff we'll need to fix this bug that you reported.

**Comment by kwasniew** [comment]
@hypermats I have a PR solving this issue: https://github.com/Unleash/unleash-proxy-client-swift/pull/55 Could you test it and let me know if it works for you?

**Comment by hypermats** [comment]
Sorry for not getting back to you, I was on holiday from work. I'll have a go at testing this change when I get a chance. Thanks for looking into it.
