### ISSUE TITLE
UnleashClient.start() doesn't always call its completion handler

### ISSUE THREAD

**Issue by MielchenWafios** [Unleash/unleash-proxy-client-swift#56]
### Describe the bug

There are situations where the completion handler of `UnleashClient.start()` won't get called - which leads to a leaked continuation error if the method got called whitin a `withCheckedContinuation` block.

That happens when the url request to fetch feature flags in `Poller.getFeatures()` fails and therefor a response parsing fails.

### Steps to reproduce the bug

1. Configure an UnlieashClient object with:
`let client = UnleashProxyClientSwift.UnleashClient(unleashUrl: "https://some.server.com", clientKey: "someKey3472987", refreshInterval: 0)`

2. Wrap UnleashClient.start() in a withCheckedContinuation block. 
`func unleashFetch(_ client: UnleashClient) async -> [String: Bool] {
        await withCheckedContinuation { continuation in
            client.start(completionHandler: { _ in
                // ..some code
                continuation.resume(returning: [:])
            })
        }
    }`

3. Call unleashFetch() with the object initialized in step 1.

### Expected behavior

The callback of `UnleashClient.start()` should be called with an appropiate error.

### Logs, error output, etc.

```bash
SWIFT TASK CONTINUATION MISUSE: unleashFetch(_:) leaked its continuation!
2023-08-24 09:55:54.787252+0200 connectavo-U[70314:21834372] SWIFT TASK CONTINUATION MISUSE: unleashFetch(_:) leaked its continuation!
```

### Additional context

This is the query in `Poller.getFeatues()` that can fail and doesn't call the completion handler:

`session.perform(request, completionHandler: { (data, response, error) in
            if let httpResponse = response as? HTTPURLResponse {...`

And while looking at this method - inside the above metioned query block - there are only individual if queries and no else. So if none of the if queries is true, the completion will also not be called.

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

unleash-proxy-client-swift, 0.0.11

**Comment by FredrikOseberg** [comment]
@MielchenWafios Thanks for the report. How would you propose to solve this issue?

**Comment by MielchenWafios** [comment]
@FredrikOseberg 

I would add more values to the enum PollerError: `noResponse, unhandledStatusCode`

And then i would alter the function below to look like this:

    
    func getFeatures(context: [String: String], completionHandler: ((PollerError?) -> Void)? = nil) -> Void {
        guard let url = formatURL(context: context) else {
            completionHandler?(.url)
            Printer.printMessage("Invalid URL")
            return
        }

        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(self.apiKey, forHTTPHeaderField: "Authorization")
        request.setValue(self.etag, forHTTPHeaderField: "If-None-Match")
        request.cachePolicy = .reloadIgnoringLocalCacheData
        
        session.perform(request, completionHandler: { (data, response, error) in
            guard let httpResponse = response as? HTTPURLResponse else {
                Printer.printMessage("No response")
                completionHandler?(.noResponse)
                return
            }

            if httpResponse.statusCode == 304 {
                completionHandler?(nil)
                Printer.printMessage("No changes in feature toggles.")
                return
            }
                
            if httpResponse.statusCode > 399 && httpResponse.statusCode < 599 {
                completionHandler?(.network)
                Printer.printMessage("Error fetching toggles")
                return
            }
                
            guard let data = data else {
                completionHandler?(nil)
                Printer.printMessage("No response data")
                return
            }

            guard httpResponse.statusCode == 200 else {
                Printer.printMessage("Unhandled status code")
                completionHandler?(.unhandledStatusCode)
                return
            }

            var result: FeatureResponse?
                    
            if let etag = httpResponse.allHeaderFields["Etag"] as? String, !etag.isEmpty {
                self.etag = etag
            }
                    
            do {
                result = try JSONDecoder().decode(FeatureResponse.self, from: data)
            } catch {
                Printer.printMessage(error.localizedDescription)
            }
                    
            guard let json = result else {
                completionHandler?(.decoding)
                return
            }
                    
            self.toggles = self.createFeatureMap(features: json)
                
            if (self.ready) {
                SwiftEventBus.post("update")
            } else {
                SwiftEventBus.post("ready")
                self.ready = true
            }
                    
            completionHandler?(nil)
        })
    }

**Comment by MielchenWafios** [comment]
**Note**
I created 2 pull requests.
* One is the change i proposed to fix this - in my opinion - bug.
* The other one is a small update to the readme that clarifies that one can set 0 as value for the refreshInterval parameter to disable periodic pulling.

**Comment by FredrikOseberg** [comment]
@MielchenWafios Fantastic. I just merged both of them, will create a new release tomorrow.

**Comment by FredrikOseberg** [comment]
I need to perform some final validations, will release the new version when I've validated.
