### ISSUE TITLE
Randomly crash after upgrade version from 0.0.6 to 1.0.3 on DictionaryStorageProvider.value.

### ISSUE THREAD

**Issue by loongman** [Unleash/unleash-proxy-client-swift#78]
### Describe the bug

According to the crash reports, seems the crash is happen when we use `UnleashClientBase.isEnabled` or `UnleashClientBase.getVariant` right after we get the `"ready"` subscription callback.

`public func subscribe(name: String, callback: @escaping () -> Void)`

Btw, there is guarantee on our implementation to always use Unleash APIs on main thread.

### Steps to reproduce the bug

The reproduce rate is not high, actually, we do not manage to reproduce it by ourselves. However, we are receiving crash reports intermittently after we release our product yesterday.

### Expected behavior

No crash.

### Screenshots

![crash_report](https://github.com/Unleash/unleash-proxy-client-swift/assets/2167359/c073fce5-89d1-4d8b-b2d3-444cc15b1eff)

### Unleash version

1.0.3

### Subscription type

None

### Hosting type

None

**Comment by loongman** [comment]
Thanks. @FredrikOseberg 

As mentioned on the issue description, according to the crash reports, seems the crash is happen when we use UnleashClientBase.isEnabled or UnleashClientBase.getVariant right after we get the "ready" subscription callback.

Below is the screenshot which provides an overview about the reports which received so far. 

<img width="1535" alt="Screenshot 2023-12-01 at 14 05 40" src="https://github.com/Unleash/unleash-proxy-client-swift/assets/2167359/495aa78d-4f1f-4f33-8a21-24880564a5ca">

We are now plan to make a small change(see below code snippet) and release it as a patch to see if it helps. If not, we has to rollback to v0.0.6 before you guys have figured out the root cause for the issue.

<img width="667" alt="Screenshot 2023-12-01 at 14 11 36" src="https://github.com/Unleash/unleash-proxy-client-swift/assets/2167359/59ee66b3-aa23-4f19-a328-cbe9ccfb519b">

**Comment by FredrikOseberg** [comment]
> Thanks. @FredrikOseberg
> 
> As mentioned on the issue description, according to the crash reports, seems the crash is happen when we use UnleashClientBase.isEnabled or UnleashClientBase.getVariant right after we get the "ready" subscription callback.
> 
> Below is the screenshot which provides an overview about the reports we received so far.
> 
> <img alt="Screenshot 2023-12-01 at 14 05 40" width="1535" src="https://private-user-images.githubusercontent.com/2167359/287164704-495aa78d-4f1f-4f33-8a21-24880564a5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTM2ODYsIm5iZiI6MTcwMTQxMzM4NiwicGF0aCI6Ii8yMTY3MzU5LzI4NzE2NDcwNC00OTVhYTc4ZC00ZjFmLTRmMzMtOGEyMS0yNDg4MDU2NGE1Y2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDY0OTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzljNjQ0ZTJiM2RkODg1MzE4OTE0N2NlMTFhZDE1YTNjYjNiYWIyOGRmOTY0ZDE5NDAxZjI1NWZjNTQzMzZhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tm-NMDQkwM8uGXROiD0CSRJd3SENXagpv0dZdedGZv4">
> We are now plan to make a small change(see below code snippet) and release it as a patch to see if it helps. If not, we has to rollback to v0.0.6 before you guys figured out the root cause of the issue.
> 
> <img alt="Screenshot 2023-12-01 at 14 11 36" width="667" src="https://private-user-images.githubusercontent.com/2167359/287169166-59ee66b3-aa23-4f19-a328-cbe9ccfb519b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTM2ODYsIm5iZiI6MTcwMTQxMzM4NiwicGF0aCI6Ii8yMTY3MzU5LzI4NzE2OTE2Ni01OWVlNjZiMy1hYTIzLTRmMTktYTMyOC1jYmU5Y2NmYjUxOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDFUMDY0OTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTIwNDc2ZDI5ZTkzN2YwNjM1MTQ2MDVlYmZiOTcxOTg4NDE3OTYyNWFmNmU3Y2VkMzdmMThiMzVkNDlmYmUwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WZOlyXXzK4NhO7pNsOUrH9JOsKc_8JhIl6DWfAv_6yM">

@loongman According to my findings yesterday, this seems to be a concurrency issue that occurs when the SDK has fetched feature toggles from the API and is calling the createFeatureMap function that puts the data into the dictionary at the exact same time as a thread is trying to read from it. I'm looking into possible solutions and should have a fix out this morning. What worked for me yesterday was wrapping the DictionaryProvider with nslock:

```
public class DictionaryStorageProvider: StorageProvider {
    private var storage: [String: Toggle] = [:]
    private let lock = NSLock()

    public init() {}

    public func set(value: Toggle?, key: String) {
        lock.lock()
        defer { lock.unlock() }
        storage[key] = value
    }

    public func value(key: String) -> Toggle? {
        lock.lock()
        defer { lock.unlock() }
        return storage[key]
    }
    
    public func clear() {
        lock.lock()
        defer { lock.unlock() }
        storage = [:]
    }
}
```

It's possible in the SDK to input your own poller implementation and thus pass the poller your own storageprovider, so if you don't have time for me to get the fix out this morning that could be an option. I'm currently evaluating if this is the best approach or if I should just create a new dict when the SDK receives new data and replace the current one after I put all the data into it. This will be my top priority until the fix is out. I'll keep you posted.

**Comment by FredrikOseberg** [comment]
@loongman I've released a new version that should resolve this issue. Can you try version 1.1.1?

**Comment by FredrikOseberg** [comment]
@loongman Fantastic. I'm glad it's resolved!
