### ISSUE TITLE
Toggles parse error

### ISSUE THREAD

**Issue by makunterry** [Unleash/unleash-proxy-client-swift#83]
### Describe the bug

Hi experts, I met with an error when the proxy sdk try to decode the api/frontend response from server, the response string is:
```
{"toggles":[{"name":"Android-FeatureFlag-Demo","enabled":true,"impressionData":false},{"name":"Android-FeatureFlag-Test","enabled":true,"impressionData":false}]}
```
And the expection throwed when decoding the data:
![image](https://github.com/Unleash/unleash-proxy-client-swift/assets/11314597/3d38a8e3-e889-49ff-aded-64e10ce074e7)

I think it should be related with the toggle definition that missing some field like 'impressionData'.
![image](https://github.com/Unleash/unleash-proxy-client-swift/assets/11314597/53ff5b3a-f446-49c0-baa2-0e1d85d4c540)

Will this be fixed soon? or is there some mismatch with the server version?
BTW, I am using the sdk version 1.2.0.

### Unleash version

1.2.0

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

ios swift sdk

**Comment by kwasniew** [comment]
Can you check if this code https://github.com/Unleash/unleash-proxy-client-swift/pull/84 works for you?

**Comment by makunterry** [comment]
@kwasniew 
Thanks for your responding, the changed Toggle definition works well on my side.
