### ISSUE TITLE
Gitlab integration not working

### ISSUE THREAD

**Issue by dchohfi** [Unleash/unleash-proxy-client-swift#9]
Hey, trying to make it work with [gitlab feature flag](https://docs.gitlab.com/ee/operations/feature_flags.html) and lib dons't seem to be working properly.

Looking at unleash oficial [api documentation](https://docs.getunleash.io/api/client/features), it requires that we send two headers to authenticate it, which doing this way returns me the correct data.

```
HEADERS:

UNLEASH-APPNAME: appName
UNLEASH-INSTANCEID: instanceId
```

But it seems that this lib is sending `appName` as a query param and the `instanceId` as `Authorization` header, which gives me `404` on Gitlab.

**Comment by ivarconr** [comment]
Hi there @dchohfi 👋🏼 

This SDK is meant to connect to the Unleash Proxy which again connects to a unleash-api.

https://docs.getunleash.io/sdks/unleash-proxy

**Comment by dchohfi** [comment]
Hey @ivarconr, fix for your fast reply!

Ok, that answer a lot of questions, sorry about that.
